### ISSUE TITLE
When gem updates on rubygems

### ISSUE THREAD

**Issue by jalkoby** [xinuc/ekuseru#2]
Last commit on github, removed backward capability to rails 2 and deprecated warning in rails. But on rubygems, as main source of gems for ruby community, changes are not published. So the question is when you will publish it? Its very important for my project.

**Comment by xinuc** [comment]
Hi,
I haven't really tested the new changes yet.
Can you try it from the git master?
If everything is fine, I'll release it soon

Thanks

**Comment by jalkoby** [comment]
Yes, now i using git version in development. But for production version, it will be bad decision, as for me. So, can I help you test gem?

**Comment by xinuc** [comment]
How is it in your dev environment? Is there any issue?

If not, I will release it now.

**Comment by xinuc** [comment]
Btw, I'm not using and actively maintaining this gem.
Are you insterested maintain it?

**Comment by jalkoby** [comment]
yes, my future projects will need that gem and I can work on it

**Comment by xinuc** [comment]
I've pushed the new gem and added you as repo collab.
Or you can fork the project if you want, and we can make your fork the canonical repo.

I'll add you as the gem owner. Can you give me your rubygems email address?

**Comment by jalkoby** [comment]
jalkoby91@gmail.com

**Comment by xinuc** [comment]
Ok, added.

Thanks very much :)
